### ISSUE TITLE
No module named 'similiarities'

### ISSUE THREAD

**Issue by lintangsutawika** [snipsco/ntm-lasagne#31]
Hi, I've followed your instructions but seem to have an error about the absence of a certain module even though it should be there?

```
Traceback (most recent call last):
  File "examples/copy-task.py", line 13, in <module>
    from ntm.layers import NTMLayer
  File "/home/lintangsutawika/anaconda3/lib/python3.5/site-packages/NTM_Lasagne-0.2.0-py3.5.egg/ntm/__init__.py", line 2, in <module>
    from . import heads
  File "/home/lintangsutawika/anaconda3/lib/python3.5/site-packages/NTM_Lasagne-0.2.0-py3.5.egg/ntm/heads.py", line 11, in <module>
    import similarities
ImportError: No module named 'similarities'
```

I wonder what is wrong, could it be the my environment?

**Comment by tristandeleu** [comment]
Hi! This looks like an issue with the way imports work in Python 3. I have developed and tested the library with Python 2 in mind unfortunately. I'll try to make the library Python 3 compatible at some point (hopefully soon!).

**Comment by lintangsutawika** [comment]
Yeah, I changed to python 2.7 and it works. Thanks!
